# Generated by Django 4.2.3 on 2023-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('tech', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('photo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
